stages:
- test
- release
- lint

test:
  stage: test
  script:
  - ./gradlew testDebugUnitTest

build:
  stage: release
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk
  script:
  - ./gradlew assembleDebug

lint:
  stage: lint
  artifacts:
    paths:
    - app/build/reports/lint-results.html
  script:
  - ./gradlew lint
