stages:
- test
- release
- lint

test:
  stage: test
  script:
  - ./gradlew testDebugUnitTest

build:
  stage: release
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk
  script:
  - ./gradlew assembleDebug
  - cp `find -iname '*.apk'` $WEBSITE_ROOT/ark-browser/app-debug-$CI_COMMIT_BRANCH.apk

lint:
  stage: lint
  artifacts:
    paths:
    - app/build/reports/lint-results.html
  script:
  - ./gradlew lint
  - cp `find -name lint-results.html` $WEBSITE_ROOT/ark-browser/
