[package]
name = "arklib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
crc32fast = "1.3.0"
env_logger = "0.9.0"
