#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook, ktlintCheck in progress..."
echo "*********************************************************"

./gradlew ktlintCheck

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "ktlintCheck found violations it could not fix."
    echo "Run ./gradlew ktlintFormat to fix formatting related issues..."
    echo "*********************************************************"
    exit 1
fi
