#!/bin/bash

echo "Changed Kotlin source files:"

if ! git diff --name-only --cached --relative | grep '\.kt[s"]\?$'
then
    echo "(no Kotlin code changed)"
    echo
    exit 0
fi

echo
echo "Running ktlintCheck..."

if ! ./gradlew ktlintCheck
then
    echo "Run ./gradlew ktlintFormat to attempt automatic fixure"
    exit 1
fi
