name: Build the app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug arm64-v8a APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-arm64-v8a-apk
        path: ./app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

    - name: Upload Debug armeabi-v7a APK
      uses: actions/upload-artifact@v2
      with:
          name: debug-armeabi-v7a-apk
          path: ./app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk

    - name: Upload Debug universal APK
      uses: actions/upload-artifact@v2
      with:
          name: debug-universal-apk
          path: ./app/build/outputs/apk/debug/app-universal-debug.apk

    - name: Upload Release arm64-v8a APK
      uses: actions/upload-artifact@v2
      with:
          name: release-arm64-v8a-apk
          path: ./app/build/outputs/apk/release/app-arm64-v8a-release.apk

    - name: Upload Release armeabi-v7a APK
      uses: actions/upload-artifact@v2
      with:
          name: release-armeabi-v7a-apk
          path: ./app/build/outputs/apk/release/app-armeabi-v7a-release.apk

    - name: Upload Release universal APK
      uses: actions/upload-artifact@v2
      with:
          name: release-universal-apk
          path: ./app/build/outputs/apk/release/app-universal-release.apk

    - name: Run linter
      run: ./gradlew lint

    - uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: ./app/build/reports/lint-results.html

    - name: Kotlin linter
      run: ./gradlew ktlintCheck
